package curso.java.tienda.entity;

// default package
// Generated 8 nov 2021 11:00:26 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetodosPago generated by hbm2java
 */
@Entity
@Table(name = "metodos_pago", catalog = "tienda_saul_refoyo_ferrero")
public class MetodosPago implements java.io.Serializable {

	private Integer id;
	private String metodoPago;

	public MetodosPago() {
	}

	public MetodosPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "metodo_pago")
	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

}
