package curso.java.tienda.entity;

// default package
// Generated 8 nov 2021 11:00:26 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OpcionesMenu generated by hbm2java
 */
@Entity
@Table(name = "opciones_menu", catalog = "tienda_saul_refoyo_ferrero")
public class OpcionesMenu implements java.io.Serializable {

	private Integer id;
	private Integer idRol;
	private String nombreOpcion;
	private String grupoOpcion;
	private String urlOpcion;

	public OpcionesMenu() {
	}

	public OpcionesMenu(Integer idRol, String nombreOpcion, String grupoOpcion, String urlOpcion) {
		this.idRol = idRol;
		this.nombreOpcion = nombreOpcion;
		this.grupoOpcion = grupoOpcion;
		this.urlOpcion = urlOpcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_rol")
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre_opcion")
	public String getNombreOpcion() {
		return this.nombreOpcion;
	}

	public void setNombreOpcion(String nombreOpcion) {
		this.nombreOpcion = nombreOpcion;
	}
	
	@Column(name = "grupo_opcion")
	public String getGrupoOpcion() {
		return grupoOpcion;
	}

	public void setGrupoOpcion(String grupoOpcion) {
		this.grupoOpcion = grupoOpcion;
	}

	@Column(name = "url_opcion")
	public String getUrlOpcion() {
		return this.urlOpcion;
	}

	public void setUrlOpcion(String urlOpcion) {
		this.urlOpcion = urlOpcion;
	}

}
